[package]
name = "rust_learnings"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
cron = { path = "cron" }
aws_utils = { path = "aws_utils" }
actix-web = "4.12.1"
